services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Extcode\CartPdf\EventListener\ProcessOrderCreate\DocumentRenderer:
    tags:
      - name: event.listener
        identifier: 'cart-pdf--process-order-create--document-renderer'
        after: 'cart--process-order-create--order-number'
        before: 'cart--process-order-create--email'

  Extcode\CartPdf\Service\PdfService:
    public: true
